/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ulises
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    
    private FrmAcercaDe acercade=null;
    int nivel;
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        sistemaMenu = new javax.swing.JMenu();
        acercaDeMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        Almacen = new javax.swing.JMenu();
        articulosMenuItem = new javax.swing.JMenuItem();
        categoriaMenuItem = new javax.swing.JMenuItem();
        presentacionMenuItem = new javax.swing.JMenuItem();
        comprasMenu = new javax.swing.JMenu();
        ingresosMenuItem = new javax.swing.JMenuItem();
        preevodoresMenuItem = new javax.swing.JMenuItem();
        ventasMenu = new javax.swing.JMenu();
        ventasMenuItem = new javax.swing.JMenuItem();
        clientesMenuItem = new javax.swing.JMenuItem();
        cotizacionesMenu = new javax.swing.JMenu();
        mantenimientoMenu = new javax.swing.JMenu();
        trabajadoresMenuItem = new javax.swing.JMenuItem();
        consultasMenu = new javax.swing.JMenu();
        stockMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        desktopPane.add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 1020, 560);

        sistemaMenu.setMnemonic('f');
        sistemaMenu.setText("Sistema");
        sistemaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sistemaMenuActionPerformed(evt);
            }
        });

        acercaDeMenuItem.setText("Acerca de");
        acercaDeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeMenuItemActionPerformed(evt);
            }
        });
        sistemaMenu.add(acercaDeMenuItem);

        salirMenuItem.setMnemonic('x');
        salirMenuItem.setText("Salir");
        sistemaMenu.add(salirMenuItem);

        menuBar.add(sistemaMenu);

        Almacen.setMnemonic('e');
        Almacen.setText("Almacen");

        articulosMenuItem.setMnemonic('t');
        articulosMenuItem.setText("Articulos");
        Almacen.add(articulosMenuItem);

        categoriaMenuItem.setMnemonic('y');
        categoriaMenuItem.setText("Categoria");
        categoriaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaMenuItemActionPerformed(evt);
            }
        });
        Almacen.add(categoriaMenuItem);

        presentacionMenuItem.setMnemonic('p');
        presentacionMenuItem.setText("Presentacion");
        Almacen.add(presentacionMenuItem);

        menuBar.add(Almacen);

        comprasMenu.setMnemonic('h');
        comprasMenu.setText("Compras");

        ingresosMenuItem.setMnemonic('c');
        ingresosMenuItem.setText("Ingresos");
        comprasMenu.add(ingresosMenuItem);

        preevodoresMenuItem.setMnemonic('a');
        preevodoresMenuItem.setText("Proveedores");
        comprasMenu.add(preevodoresMenuItem);

        menuBar.add(comprasMenu);

        ventasMenu.setText("Ventas");

        ventasMenuItem.setText("Ventas");
        ventasMenu.add(ventasMenuItem);

        clientesMenuItem.setText("Clientes");
        ventasMenu.add(clientesMenuItem);

        menuBar.add(ventasMenu);

        cotizacionesMenu.setText("Cotizaciones");
        menuBar.add(cotizacionesMenu);

        mantenimientoMenu.setText("Mantenimiento");

        trabajadoresMenuItem.setText("Trabajadores");
        mantenimientoMenu.add(trabajadoresMenuItem);

        menuBar.add(mantenimientoMenu);

        consultasMenu.setText("Consultas");

        stockMenuItem.setText("Stock articulos");
        consultasMenu.add(stockMenuItem);

        menuBar.add(consultasMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoriaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaMenuItemActionPerformed

    private void sistemaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sistemaMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sistemaMenuActionPerformed

    private void acercaDeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeMenuItemActionPerformed
        if (acercade==null || acercade.isClosed()) {
            
            try {
                if(acercade==null || acercade.isClosed()){
                    acercade=new FrmAcercaDe();
                    this.jDesktopPane1.add(acercade);
                }
                acercade.setVisible(true);
                
            } catch (Exception ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_acercaDeMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Almacen;
    private javax.swing.JMenuItem acercaDeMenuItem;
    private javax.swing.JMenuItem articulosMenuItem;
    private javax.swing.JMenuItem categoriaMenuItem;
    private javax.swing.JMenuItem clientesMenuItem;
    private javax.swing.JMenu comprasMenu;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JMenu cotizacionesMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem ingresosMenuItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu mantenimientoMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem preevodoresMenuItem;
    private javax.swing.JMenuItem presentacionMenuItem;
    private javax.swing.JMenuItem salirMenuItem;
    private javax.swing.JMenu sistemaMenu;
    private javax.swing.JMenuItem stockMenuItem;
    private javax.swing.JMenuItem trabajadoresMenuItem;
    private javax.swing.JMenu ventasMenu;
    private javax.swing.JMenuItem ventasMenuItem;
    // End of variables declaration//GEN-END:variables

}
